Repository AY2021S1-CS2103T-W12-1/tp, pull requests merged in 2020-09, with the labels that each got.

#12 Update EditCommand function
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPatientCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditPatientCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: Priority.Medium, type.Story

#15 Update UG for addPatient command
  docs/UserGuide.md
Labels: documentation

#24 Complete basic UI for Covigent
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/covigent_logo.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement

#26 Add Room class
  README.md
  Ui.png
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddNumberOfRoomsCommand.java
  src/main/java/seedu/address/logic/commands/AddRoomsCommand.java
  src/main/java/seedu/address/logic/commands/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/SearchPatientCommand.java
  src/main/java/seedu/address/logic/parser/AddRoomsParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomBook.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/hotel/Room.java
  src/main/java/seedu/address/model/tasks/Task.java
  src/main/java/seedu/address/storage/RoomOccupancyStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRoomsCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRoomsParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/RoomBookTest.java
  src/test/java/seedu/address/model/hotel/RoomTest.java
  src/test/java/seedu/address/storage/RoomOccupancyStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: Priority.High, Type.BugFix, Type.Enhancement, Type.Story
