Repository AY2021S1-CS2103T-W12-1/tp, pull requests merged in 2020-10, with the labels that each got.

#46 update UG with searchpatient command
  docs/UserGuide.md
Labels: Type.Documentation

#59 Code cleanup
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/patient/EmailTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: Type.Documentation, Type.Enhancement

#25 Update UI to include rooms and room details
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/patient/ListPatientCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/RoomList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/java/seedu/address/ui/RoomDetailsPanel.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/covigent_logo.png
  src/main/resources/images/green_circle.png
  src/main/resources/images/red_circle.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RoomDetailsPanel.fxml
  src/main/resources/view/RoomListCard.fxml
  src/main/resources/view/RoomListPanel.fxml
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/room/RoomTest.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: Type.Enhancement

#60 Add deletepatient Command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/patient/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/SearchPatientCommand.java
  src/main/java/seedu/address/logic/parser/patient/DeletePatientCommandParser.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/patient/AddPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/patient/DeletePatientCommandParserTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: Priority.High, Type.Feature

#27 Add addtask command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/patient/PatientCliSyntax.java
  src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/TaskCliSyntax.java
  src/main/java/seedu/address/logic/parser/task/TaskParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/RoomList.java
  src/main/java/seedu/address/model/room/exceptions/RoomNotFoundException.java
  src/main/java/seedu/address/model/task/DateTimeDue.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
  src/main/java/seedu/address/model/tasks/Task.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/JsonSerializableRoomListTest/typicalRoomsInRoomList.json
  src/test/java/seedu/address/logic/commands/NewCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/task/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TaskParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/room/RoomIntegrationTest.java
  src/test/java/seedu/address/model/room/RoomListIntegrationTest.java
  src/test/java/seedu/address/model/room/RoomTest.java
  src/test/java/seedu/address/model/task/DateTimeDueTest.java
  src/test/java/seedu/address/model/task/DescriptionTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRoomTest.java
  src/test/java/seedu/address/storage/JsonRoomOccupancyStorageTest.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High, Type.Feature, Type.Story

#72 Add editroom command for rooms
  .gitignore
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/patient/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RoomParserUtil.java
  src/main/java/seedu/address/logic/parser/patient/EditPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/InitRoomsCommandParser.java
  src/main/java/seedu/address/logic/parser/room/RoomCliSyntax.java
  src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/RoomList.java
  src/main/java/seedu/address/model/room/exceptions/DuplicateRoomException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RoomDetailsPanel.java
  src/test/data/JsonRoomOccupancyStorageTest/SomeFile.json
  src/test/data/JsonRoomOccupancyStorageTest/roomsOccupied.jason
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/patient/EditPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/AddRoomsParserTest.java
  src/test/java/seedu/address/logic/parser/room/EditRoomCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditRoomDescriptorBuilder.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.Medium, Type.Feature

#82 Add noorul find and list
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/ListRoomCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/RoomList.java
  src/main/java/seedu/address/storage/JsonSerializableRoomList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/test/java/seedu/address/logic/commands/room/ListCommandTest.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High

#83 Add searchtask command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/task/SearchTaskCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/logic/parser/task/SearchTaskCommandParser.java
  src/main/java/seedu/address/model/task/DateTimeDue.java
  src/test/java/seedu/address/logic/commands/task/SearchTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/task/SearchTaskCommandParserTest.java
Labels: Priority.Medium, Type.Feature

#85 Fix bugs where tasklist was not being saved
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/model/room/Room.java
Labels: Priority.High, Type.BugFix

#91 Noorul fix duplicate room
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/ListRoomCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/storage/JsonSerializableRoomList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/room/FindRoomCommandTest.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High

#89 Add edittask command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/TaskCliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/task/EditTaskCommandParserTest.java
  src/test/java/seedu/address/model/room/RoomIntegrationTest.java
  src/test/java/seedu/address/model/room/RoomListIntegrationTest.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High, Type.Feature, Type.Story

#90 Complete SearchRoomCommand
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/ListRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/SearchRoomCommand.java
  src/main/java/seedu/address/logic/parser/patient/DeletePatientCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PatientRecords.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/data/JsonSerializableRoomListTest/typicalRoomsInRoomList.json
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/FindPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/ListPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/SearchPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/room/ListRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/patient/DeletePatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
  src/test/java/seedu/address/model/PatientRecordsTest.java
  src/test/java/seedu/address/model/patient/NameTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/patient/UniquePatientListTest.java
  src/test/java/seedu/address/storage/JsonPatientRecordsStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializablePatientRecordsTest.java
  src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.Medium, Type.BugFix, Type.Documentation, Type.Feature

#99 Complete SearchRoomCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/room/SearchRoomCommand.java
  src/main/java/seedu/address/logic/parser/patient/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/room/SearchRoomCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomList.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
  src/test/java/seedu/address/testutil/SearchRoomDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.Medium, Type.Feature

#100 Improvement for UI
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/FindPatientCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/SearchTaskCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/logic/parser/patient/EditPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/patient/FindPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/room/InitRoomCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/java/seedu/address/ui/RoomDetailsPanel.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/main/resources/images/patient_icon.png
  src/main/resources/images/task_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RoomDetailsPanel.fxml
  src/main/resources/view/RoomDetailsPanelStyle.css
  src/main/resources/view/RoomListPanel.fxml
  src/main/resources/view/RoomListView.css
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/FindPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/AddRoomsCommandTest.java
  src/test/java/seedu/address/logic/commands/room/FindRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/patient/EditPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/patient/FindPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/AddRoomsParserTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Type.BugFix, Type.Enhancement

#101 Update color scheme of UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/CommandBox.css
  src/main/resources/css/Extensions.css
  src/main/resources/css/ListCard.css
  src/main/resources/css/ListPanel.css
  src/main/resources/css/MainWindow.css
  src/main/resources/css/ResultDisplay.css
  src/main/resources/css/RoomDetailsPanel.css
  src/main/resources/css/StatusBarFooter.css
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/RoomDetailsPanel.fxml
  src/main/resources/view/RoomListCard.fxml
  src/main/resources/view/RoomListPanel.fxml
  src/main/resources/view/RoomListView.css
  src/main/resources/view/StatusBarFooter.fxml
Labels: Priority.Low, Type.Enhancement

#106 Bug fix json adapted task
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: Priority.High, Type.BugFix

#105 Add images to tab and include logo
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/resources/css/MainWindow.css
  src/main/resources/css/ResultDisplay.css
  src/main/resources/css/StatusBarFooter.css
  src/main/resources/images/logo.png
  src/main/resources/images/patient.png
  src/main/resources/images/room.png
  src/main/resources/images/task.png
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/RoomListCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: Priority.Low, Type.Enhancement

#109 Fix bug where editpatient crashes the app
  src/main/java/seedu/address/model/ModelManager.java
Labels: Priority.High, Type.BugFix

#107 Refactor ParserUtil into PatientParserUtil
  src/main/java/seedu/address/logic/commands/task/SearchTaskCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RoomParserUtil.java
  src/main/java/seedu/address/logic/parser/patient/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/patient/DeletePatientCommandParser.java
  src/main/java/seedu/address/logic/parser/patient/EditPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/patient/PatientParserUtil.java
  src/main/java/seedu/address/logic/parser/patient/SearchPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/InitRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/SearchRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/SearchTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/NewCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/patient/PatientParserUtilTest.java
  src/test/java/seedu/address/logic/parser/room/EditRoomCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
Labels: Priority.Low, Type.CodeQuality

#98 Add Task UI
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/SearchTaskCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/task/DateTimeDue.java
  src/main/java/seedu/address/model/task/DueDatePredicate.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonTaskOccupancyStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/ListPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/SearchPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/AddRoomsCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/FindRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/ListRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High, Type.Feature

#115 Fix bug where task commands work with room index instead of room numbers
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/SearchRoomCommand.java
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/EditTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/NewCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/task/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/EditTaskCommandParserTest.java
  src/test/java/seedu/address/model/RoomListTest.java
  src/test/java/seedu/address/model/room/RoomListIntegrationTest.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High, Type.BugFix

#134 Bugfix deletepatient
  build.gradle
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/parser/patient/DeletePatientCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PatientRecords.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/parser/patient/DeletePatientCommandParserTest.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Type.BugFix

#135 Bugfix: Help, Exit, Editable box, PatientDetailsPanel
  build.gradle
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: Priority.High, Type.BugFix

#136 Refractor edit room
  src/main/java/seedu/address/logic/commands/room/AllocateRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/EditRoomCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/logic/parser/room/AllocateRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/EditRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/RoomCliSyntax.java
  src/main/resources/css/MainWindow.css
  src/main/resources/css/RoomDetailsPanel.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RoomDetailsPanel.fxml
  src/test/java/seedu/address/logic/commands/NewCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/EditRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/room/AllocateRoomCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/EditRoomCommandParserTest.java
  src/test/java/seedu/address/testutil/AllocateRoomDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditRoomDescriptorBuilder.java
Labels: Priority.Medium, Type.BugFix

#139 Fix Tab UI and Covigent Logo
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/MainWindow.css
  src/main/resources/images/address_book_32.png
  src/main/resources/images/covigent.png
  src/main/resources/images/covigent_logo.png
  src/main/resources/images/patientlogo.png
  src/main/resources/images/room.png
  src/main/resources/images/roomlogo.png
  src/main/resources/images/rooms.png
  src/main/resources/images/tasklogo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: Priority.Medium, Type.Enhancement

#138 Refactor NewCommandTestUtil
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/NewCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/ListPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/SearchPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/AddRoomsCommandTest.java
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/FindRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/ListRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/patient/AddPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/patient/EditPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/patient/SearchPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/AllocateRoomCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/EditTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/SearchTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TaskParserUtilTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/room/RoomListIntegrationTest.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
  src/test/java/seedu/address/testutil/command/GeneralCommandTestUtil.java
  src/test/java/seedu/address/testutil/command/PatientCommandTestUtil.java
  src/test/java/seedu/address/testutil/command/RoomCommandTestUtil.java
  src/test/java/seedu/address/testutil/command/TaskCommandTestUtil.java
Labels: Priority.Medium, Type.CodeQuality

#142 Add listTask function and fix UI bug to display storage of task in task tab
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/CommandBox.png
  docs/images/commandhighlight.PNG
  docs/images/infoicon.PNG
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/task/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/main/java/seedu/address/storage/JsonTaskStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/task/ListTaskCommandTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High, Type.BugFix, Type.Feature, Type.Test

#143 Test for ModelManager
  src/main/java/seedu/address/logic/commands/patient/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/room/AllocateRoomCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/RoomCard.java
  src/main/java/seedu/address/ui/RoomDetailsPanel.java
  src/main/java/seedu/address/ui/RoomListPanel.java
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
Labels: Priority.Low, Type.Test

#151 Bug fix
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/room/AllocateRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java
  src/main/java/seedu/address/logic/commands/task/SearchTaskCommand.java
  src/main/java/seedu/address/logic/parser/room/AllocateRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/InitRoomCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyRoomList.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/UniqueRoomList.java
  src/main/java/seedu/address/model/room/ComparableRoom.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/storage/JsonAdaptedRoom.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonRoomOccupancyStorage.java
  src/main/java/seedu/address/storage/JsonSerializableRoomList.java
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/main/java/seedu/address/storage/JsonTaskStorage.java
  src/main/java/seedu/address/storage/RoomRecordsStorage.java
  src/test/data/JsonSerializableRoomListTest/typicalRoomsInRoomList.json
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/room/InitRoomParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/RoomListTest.java
  src/test/java/seedu/address/model/UniqueRoomListTest.java
  src/test/java/seedu/address/model/room/RoomIntegrationTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Type.BugFix

#148 Improve code quality
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/patient/AddPatientCommand.java
  src/main/java/seedu/address/logic/commands/patient/DeletePatientCommand.java
  src/main/java/seedu/address/logic/commands/room/FindRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/SearchRoomCommand.java
  src/main/java/seedu/address/logic/commands/task/SearchTaskCommand.java
  src/main/java/seedu/address/logic/parser/CovigentAppParser.java
  src/main/java/seedu/address/logic/parser/patient/AddPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/patient/PatientParserUtil.java
  src/main/java/seedu/address/logic/parser/room/SearchRoomCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/Age.java
  src/main/java/seedu/address/model/patient/Comment.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/PeriodOfStay.java
  src/main/java/seedu/address/model/patient/Temperature.java
  src/main/java/seedu/address/model/patient/TemperatureRangePredicate.java
  src/main/resources/css/Extensions.css
  src/main/resources/css/ListPanel.css
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/AddPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/SearchPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/ListRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/task/SearchTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/patient/AddPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/patient/AgeTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/patient/PeriodOfStayTest.java
  src/test/java/seedu/address/model/patient/TemperatureTest.java
  src/test/java/seedu/address/model/patient/UniquePatientListTest.java
  src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/SearchRoomDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.Medium, Type.BugFix, Type.CodeQuality

#156 Improve code quality
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/patient/Age.java
  src/main/java/seedu/address/model/patient/Comment.java
  src/main/java/seedu/address/model/patient/PeriodOfStay.java
  src/main/java/seedu/address/model/task/DueDatePredicate.java
  src/main/java/seedu/address/model/task/TaskList.java
  src/main/java/seedu/address/storage/JsonTaskStorage.java
  src/main/java/seedu/address/ui/PatientDetailsPanel.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/resources/images/test.jpg
  src/test/java/seedu/address/logic/commands/patient/DeletePatientCommandTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/parser/patient/EditPatientCommandParserTest.java
  src/test/java/seedu/address/testutil/AllocateRoomDescriptorBuilder.java
Labels: Priority.Low, Type.CodeQuality
