Repository AY2021S1-CS2103T-W12-1/tp, pull requests merged in 2020-11, with the labels that each got.

#214 Handle bug report
  src/main/java/seedu/address/logic/commands/room/AllocateRoomCommand.java
  src/main/java/seedu/address/logic/commands/room/SearchRoomCommand.java
  src/main/java/seedu/address/logic/parser/room/AllocateRoomCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/main/java/seedu/address/storage/JsonAdaptedRoom.java
  src/main/java/seedu/address/ui/RoomDetailsPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/css/RoomDetailsPanel.css
  src/main/resources/images/appLogo.jpg
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientDetailsPanel.fxml
  src/main/resources/view/RoomDetailsPanel.fxml
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandTest.java
  src/test/java/seedu/address/logic/commands/room/SearchRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/room/AllocateRoomCommandParserTest.java
  src/test/java/seedu/address/testutil/AllocateRoomDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RoomBuilder.java
Labels: Priority.Medium, Type.BugFix

#227 Fix task index not updating in search results
  src/main/java/seedu/address/ui/RoomTaskDetailsPanel.java
  src/main/java/seedu/address/ui/RoomTaskListPanel.java
Labels: Priority.High, Type.BugFix

#228 Set minimum and maximum length of task description
  src/main/java/seedu/address/logic/parser/task/TaskParserUtil.java
  src/main/java/seedu/address/model/task/Description.java
  src/test/java/seedu/address/model/task/DescriptionTest.java
Labels: Priority.Low, Type.BugFix

#230 Update error message for parsing room and task numbers
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/room/AllocateRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/room/SearchRoomCommandParser.java
  src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/task/EditTaskCommandParser.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/EditTaskCommandParserTest.java
Labels: Priority.Low, Type.BugFix

#224 Bug fix noorul ped
  docs/UserGuide.md
  docs/team/itssodium.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java
  src/main/java/seedu/address/logic/parser/room/InitRoomCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/main/java/seedu/address/storage/JsonAdaptedRoom.java
  src/main/java/seedu/address/storage/JsonSerializableRoomList.java
  src/test/data/JsonSerializableRoomListTest/notCorrectOrder.json
  src/test/data/JsonSerializableRoomListTest/notCorrectStartRooms.json
  src/test/java/seedu/address/logic/commands/room/InitRoomCommandTest.java
  src/test/java/seedu/address/logic/parser/room/InitRoomParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/room/UniqueRoomListTest.java
  src/test/java/seedu/address/storage/JsonRoomOccupancyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java
  src/test/java/seedu/address/testutil/TypicalRooms.java
  src/test/java/seedu/address/testutil/stubs/ModelStub.java
Labels: Priority.High, Type.BugFix

#236 Bugfix2
  src/main/java/seedu/address/model/PatientRecords.java
  src/main/java/seedu/address/model/patient/Age.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/main/java/seedu/address/model/patient/Temperature.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/main/java/seedu/address/storage/JsonPatientRecordsStorage.java
  src/main/java/seedu/address/storage/JsonSerializablePatientRecords.java
  src/main/java/seedu/address/storage/PatientRecordsStorage.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/model/PatientRecordsTest.java
  src/test/java/seedu/address/storage/JsonPatientRecordsStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java
  src/test/java/seedu/address/testutil/PatientRecordsBuilder.java
Labels: Priority.Low, Type.BugFix

#235 Add PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/chiamyunqing.md
  docs/team/itssodium.md
  docs/team/leemingde.md
  docs/team/raymondge.md
  docs/team/w-yeehong.md
Labels: Priority.Low, Type.Documentation

#243 Bug fix final
  docs/team/itssodium.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/room/InitRoomCommand.java
  src/main/java/seedu/address/model/RoomList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/room/Room.java
  src/main/java/seedu/address/model/room/UniqueRoomList.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/RoomRecordsStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/patient/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/patient/JsonPatientRecordsStorage.java
  src/main/java/seedu/address/storage/patient/JsonSerializablePatientRecords.java
  src/main/java/seedu/address/storage/patient/PatientRecordsStorage.java
  src/main/java/seedu/address/storage/rooms/JsonAdaptedRoom.java
  src/main/java/seedu/address/storage/rooms/JsonRoomOccupancyStorage.java
  src/main/java/seedu/address/storage/rooms/JsonSerializableRoomList.java
  src/main/java/seedu/address/storage/rooms/RoomRecordsStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRoomTest.java
  src/test/java/seedu/address/storage/JsonPatientRecordsStorageTest.java
  src/test/java/seedu/address/storage/JsonRoomOccupancyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializablePatientRecordsTest.java
  src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: Priority.Medium, Type.BugFix, Type.CodeQuality

#242 Add unit tests for task-related commands
  src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/task/EditTaskCommand.java
  src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/task/EditTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/task/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/EditTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/task/TaskParserUtilTest.java
  src/test/java/seedu/address/testutil/command/TaskCommandTestUtil.java
Labels: Priority.Low, Type.Test

#244 Add integration test for editpatientcommand and allocateroomcommand
  src/main/java/seedu/address/logic/commands/room/AllocateRoomCommand.java
  src/main/java/seedu/address/logic/parser/patient/EditPatientCommandParser.java
  src/main/java/seedu/address/logic/parser/room/AllocateRoomCommandParser.java
  src/main/java/seedu/address/model/room/Room.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/patient/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/room/AllocateRoomCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/CovigentAppParserTest.java
  src/test/java/seedu/address/logic/parser/room/AllocateRoomCommandParserTest.java
  src/test/java/seedu/address/logic/parser/room/SearchRoomCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonSerializableRoomListTest.java
  src/test/java/seedu/address/testutil/AllocateRoomDescriptorBuilder.java
  src/test/java/seedu/address/testutil/command/PatientCommandTestUtil.java
  src/test/java/seedu/address/testutil/command/RoomCommandTestUtil.java
Labels: Type.BugFix, Type.Test
